<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>f15a8cb5-5e97-4534-8db9-9f9f97592a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq241jLMTX8pKqCsLfQb4TJiGEARjZh292skYT4E7RH7qspiFir3tww-UGkT6t5xfYkj6KccvG1FsnRQ5qdYOXKgPTNW3khBrKkUBSy-_wlpM33yBhLVSYjM7ciGk3WGOn72wF9-Q2tqqfa9n7kPFu9jdrn7kOtJb9gGOrYD4WCmrqTwYoHh7_iGZSaVvEdVny-A4T0oTexV8Rlpw9zwz6E1vALZ9oo2PVoy9uwMI7uVTKkSJ2-Q&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;id=2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Katalon One/iframe_Reset Password_c-r6iwa7rlcp54</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq241jLMTX8pKqCsLfQb4TJiGEARjZh292skYT4E7RH7qspiFir3tww-UGkT6t5xfYkj6KccvG1FsnRQ5qdYOXKgPTNW3khBrKkUBSy-_wlpM33yBhLVSYjM7ciGk3WGOn72wF9-Q2tqqfa9n7kPFu9jdrn7kOtJb9gGOrYD4WCmrqTwYoHh7_iGZSaVvEdVny-A4T0oTexV8Rlpw9zwz6E1vALZ9oo2PVoy9uwMI7uVTKkSJ2-Q&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;id=2')])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
