<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>f14cd212-2cf1-4a00-b27c-a6b10b00af56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26hNf9O5pPbJvGKixt986dFpjgWACfZcuZIU_TKFwGTgRYD5eB49JNb3DEb-r4Rknn-hq0i6q9W5xnQ8x-hwaS-qA6H3w7eezRcjZFWC4lOOh-tXNvhLuZTUSJwtgoBTqyr8ilKYkIXJX6PS-yiQ6IG6FsatBUikE6Ho0uGKI0PkvjNwfGoZ8x0MTELw2oI0iwObUR_RlvfNMLGWGC9pmmZ2eBpZEkKMUe34MAnzj3MqaIBz8E&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;id=806bc61f4ef51e69</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Katalon One/iframe_Reset Password_c-r6iwa7rlcp54</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[4]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26hNf9O5pPbJvGKixt986dFpjgWACfZcuZIU_TKFwGTgRYD5eB49JNb3DEb-r4Rknn-hq0i6q9W5xnQ8x-hwaS-qA6H3w7eezRcjZFWC4lOOh-tXNvhLuZTUSJwtgoBTqyr8ilKYkIXJX6PS-yiQ6IG6FsatBUikE6Ho0uGKI0PkvjNwfGoZ8x0MTELw2oI0iwObUR_RlvfNMLGWGC9pmmZ2eBpZEkKMUe34MAnzj3MqaIBz8E&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;id=806bc61f4ef51e69')])[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
